const mongoose = require('mongoose');
const { Schema, model } = require('mongoose');

const pcSchema = new mongoose.Schema({
  'Name': { type: String },
  'Reference': { type: String },
  'Link': { type: String },
  'Description': { type: String },
  'Image': { type: String },
  'Price': { type: Number },
  'Availability': { type: String },
  'category': { type: String },
  'seller': { type: String },
  'Type': { type: String },
  'color': { type: String },
  'Operating System': { type: String },
  'CPU Type': { type: String },
  'CPU': { type: String },
  'GPU Type': { type: String },
  'GPU': { type: String },
  'RAM': { type: Number },
  'Storage': { type: String },
  'Garantie': { type: String },
  'Taille écran': { type: String },
  'Ecran tactile': { type: String },
  'Resolution': { type: String },
  'RAM_DDR_Generation': { type: String },
  'CPU Ref': { type: String },
  'GPU Ref': { type: String },
  'Poids': { type: Number },
  'Points Forts': { type: String },
  'CConnectique': { type: String },
  'Camera': { type: String },
  'Batterie': { type: String },
  'Description clavier': { type: String },
  'Taux De Rafraichissement': { type: String },
  'Type mémoire': { type: String },
  'Wifi': { type: String },
  'Bluetooth': { type: String },
  'Connecteurs': { type: String },
  'Type Stockage': { type: String },
  'Type écran': { type: String },
  'Audio': { type: String },
  'Technical Specs': { type: String },
  'Display': { type: String },
  'Réseau': { type: String },
  'Marque': { type: String },
  'Score Carte Graphique': { type: Number, default: 0 },
  'Score Cpu': { type: Number, default: 0 },
  'Score Ram': { type: Number, default: 0 },
  'Score Storage': { type: Number, default: 0 },
  'created_at': { type: Date, default: Date.now }
});

module.exports = mongoose.model('PC', pcSchema);
